version: '3'
volumes:
  dados:
networks:
  banco:
  web:
services:
  db:
    image: postgres:9.6
    volumes:
      #Volume dos dados
      - dados:/var/lib/postgresql/data
      #scripts
      - /D_DRIVE/Repos/CursoDocker/email-worker-compose/scripts:/scripts
      - /D_DRIVE/Repos/CursoDocker/email-worker-compose/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  frontend:
    image: nginx:1.13
    volumes:
      #Site
      - /D_DRIVE/Repos/CursoDocker/email-worker-compose/web:/usr/share/nginx/html/
      #Configuração do proxy reverso
      - /D_DRIVE/Repos/CursoDocker/email-worker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      #Aplicação
      - /D_DRIVE/Repos/CursoDocker/email-worker-compose/app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - banco
      - web
    depends_on:
      - db