version: '3'
volumes:
  dados:
networks:
  banco:
  web:
  fila:
services:
  db:
    image: postgres:9.6
    volumes:
      #Volume dos dados
      - dados:/var/lib/postgresql/data
      #scripts
      #- ./scripts:/scripts
      #- ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /D_DRIVE/Repos/CursoDocker/email-worker-compose/scripts:/scripts
      - /D_DRIVE/Repos/CursoDocker/email-worker-compose/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  frontend:
    image: nginx:1.13
    volumes:
      #Site
      #- ./web:/usr/share/nginx/html/
      - /D_DRIVE/Repos/CursoDocker/email-worker-compose/web:/usr/share/nginx/html/
      #Configuração do proxy reverso
      #- ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /D_DRIVE/Repos/CursoDocker/email-worker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      #Aplicação
      #- ./app:/app
      - /D_DRIVE/Repos/CursoDocker/email-worker-compose/app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue
    environment:
      - DB_NAME=xpto

  queue:
    image: redis:3.2
    networks:
      - fila
  
  worker:
    build: worker
    volumes:
      # Worker
      #- ./worker:/worker
      - /D/Repos/CursoDocker/email-worker-compose/worker:/worker
    working_dir: /worker
    command: worker.py
    networks: 
      - fila
    depends_on: 
      - queue